language: python

python:
    - 3.4

env:
    global:
        - secure: "pC2X49Av9OlrMuMJ8ypmRe3t03hc9Kn2u43syoG/P2NkSvPi8FKZqnTNlDk5UaTeZ3wnWDTM/PcmBqGqlyyMNv85+v/+yej1igzHT4kaI7kr0s0yu8o5lklfQMx9lSHNlj2JD/SRLrw/PIbBUDGGTWpVxiWw6m+AviaxAF9ULU36seDVv6Zt+u1/ApuSz34VKie+z7WCNs64mK2h47sJks5XHMGDjJ9Svrmjx2dh+93kFxL1kkdSe8GqRZ+Otzb5Zt/Ip7kI1z5BrFE0tD8mHwBWC21vZuFCv70DwPY47Hn84wyUXtqzy9K+2NulqW2Iz359bkfkPe/+QHoeNMgvLmilLbzUrR5KNPdI/hDnvu62ybwNWyrThDjd1j6vJdD6gNJyLhj3+BuwgrmdxIUADKR4Sh/Q297AJsCtRBCOvALNc81By8By1/bv9tr9pJJno4fRpyLqeUb8UVlvZS+j1+sd1d4C4sQNjOXkK4Jc+3t0Lfv2DL7OYMzBpmsiLkCgdjySJHrUrX0tclEJ+lQ6dGccjrGG1muAiePstmPH5GkeTYJMuU1hOQ8H7KEkDpT12ZUJFttyq3RlB34vQhNF0dzYlHk+GaWJhxlG3mHrCdLZFWyakX87NpaS1OmB2gv4L9TriLi71jg1fs0XUnE1auD+10XKr8Lg7rc3LshrGB4="

before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda
    - pip install nikola
    - pip install ghp-import

install:
    - nikola build

script:
    - echo "Hello"

after_success:
    - bash ./update-ghpages.sh
