language: python

python:
    - 3.4
env:
    global:
      - secure: "FOIssFIB0H/bAJQnvKJbWzIiqQOmbcPBj8v+vlQsDm3m1RP253fT/+ZZu2bfqh0Hda8W7Xo5kIPjwp9tCCec9niEGvbzidTrBxntoDakJe0a5Ep4HHmDwdxXr8NQYszf0VTr3exAVYuDJrK9plTheBXsVpRpLOC1HeUtQlx6ktEgzF/QEdlVEo3bnHI01DPNsn1tCIc85dvSVHb313854FbvZh42m7eve5egnY9nQjg9Re55vTsoSR1GfxqiM2BzMMyBcxYLMTfW3NcJc+SvQm9w45FolxP39mTMWyCLgHEAewaSLnhcg9Ry6O3THlZGiQYOx1SW5HJ9r5SRFzkuZirhcOnxJrIFHg/d4ta9ijOTqYlx+SryRmZfqpS/f+9pl2GBOvbIOMlDv4gQNm3lQNZEatc0rSXxmNDdDXgduIL/RbB8/yWQFA72xQfj1o9YPu/kRedOvBl+JTibIoh8B7l+mUla6ZXgEZZNhLLdJtWTXwZzAJmq6ihvRhDyzWp18HMvMC94BTMuTGtq0SgTxVMlWWrAMm7caixGy0ADTGz4IRUgh2pBsYaZSw93qI8/g3X4yyekoIvrbIkuL0JtqAGoWCXE/hAHiTb8CMzGC5P1wTjVLK6RdFAxW0K3gWgFWyqinwkk/WaJqDKKbDGRR/0bg+BqEtck+kV88hkZALY="
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - conda update --yes conda
install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install -y lxml requests Pygments unidecode Pillow mako natsort docutils  python-dateutil MarkupSafe six cloudpickle 
    - pip install nikola
    - pip install ghp-import
    - nikola build
script:
    - echo "Hello"
after_success:
    - bash ./update-ghpages.sh

